
ALTER TABLE item
DROP CONSTRAINT FK_HAVE;

ALTER TABLE group_order
DROP CONSTRAINT FK_INCLUDE;

ALTER TABLE restaurant
DROP CONSTRAINT FK_CONTAINTS;


ALTER TABLE delivery_info
ALTER COLUMN delivery_id TYPE VARCHAR(255);

ALTER TABLE restaurant
ALTER COLUMN restaurant_id TYPE VARCHAR(255);

ALTER TABLE group_order
ALTER COLUMN group_order_id TYPE VARCHAR(255);

ALTER TABLE admin
ALTER COLUMN admin_id TYPE VARCHAR(255);


ALTER TABLE item
ALTER COLUMN item_id TYPE VARCHAR(255);
