ALTER TABLE restaurant
ALTER COLUMN delivery_fk TYPE VARCHAR(255);

ALTER TABLE group_order
ALTER COLUMN restaurant_fk TYPE VARCHAR(255);

ALTER TABLE item
ALTER COLUMN group_order_fk TYPE VARCHAR(255);

ALTER TABLE GROUP_ORDER
    ADD CONSTRAINT FK_INCLUDE
        FOREIGN KEY (RESTAURANT_FK)
            REFERENCES RESTAURANT (RESTAURANT_ID)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;


ALTER TABLE ITEM
    ADD CONSTRAINT FK_HAVE
        FOREIGN KEY (GROUP_ORDER_FK)
            REFERENCES GROUP_ORDER (GROUP_ORDER_ID)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;


ALTER TABLE RESTAURANT
    ADD CONSTRAINT FK_CONTAINTS
        FOREIGN KEY (DELIVERY_FK)
            REFERENCES DELIVERY_INFO (DELIVERY_ID)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;
